# Generated by Django 5.1.2 on 2024-11-06 05:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="gifts/photos/"),
                ),
                ("price", models.FloatField(blank=True, null=True)),
                ("importance", models.IntegerField(blank=True, null=True)),
                (
                    "uid",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, null=True, unique=True
                    ),
                ),
            ],
        ),
    ]
