# Generated by Django 5.1.2 on 2024-11-06 05:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groom", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift",
            name="uid",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
    ]
