# Generated by Django 5.1.2 on 2024-11-06 18:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groom", "0002_alter_gift_uid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest", models.CharField(blank=True, max_length=100, null=True)),
                ("whatsapp", models.CharField(blank=True, max_length=50, null=True)),
                ("token", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "max_escorts",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AC", "Aguardando confirmação"),
                            ("C", "Confirmado"),
                            ("R", "Recusado"),
                        ],
                        default="AC",
                        max_length=2,
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
