# Generated by Django 5.1.2 on 2024-11-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groom", "0003_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="reservated",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
