# Generated by Django 5.1.2 on 2024-11-07 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groom", "0004_gift_reservated"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="reservated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="groom.guest",
            ),
        ),
    ]
